// Known-valid values for $modifier`...` / $modifiers`...` (libram's KoLmafia Modifier lookup).
// KoLmafia has no data source for these like it does for items/effects/etc, so this list is
// maintained by hand. Seeded from every value already used in packages/ - add to it as needed.
export const modifiers = [
  "Absorb Adventures",
  "Absorb Stats",
  "Accessory Drop",
  "Additional Song",
  "Adventure Randomly",
  "Adventure Underwater",
  "Adventures",
  "Alters Page Text",
  "Always Fumble",
  "Attacks Can't Miss",
  "Avatar",
  "Avoid Attack",
  "Base Resting HP",
  "Base Resting MP",
  "Blind",
  "Bonus Resting HP",
  "Bonus Resting MP",
  "Booze Drop",
  "Booze Fairy",
  "Booze Fairy Effectiveness",
  "Breakable",
  "Brimstone",
  "Buffed HP Maximum",
  "Buffed MP Maximum",
  "Buffed Moxie",
  "Buffed Muscle",
  "Buffed Mysticality",
  "Candy Drop",
  "Candy Fairy",
  "Candy Fairy Effectiveness",
  "Class",
  "Cloathing",
  "Clowniness",
  "Cold Damage",
  "Cold Immunity",
  "Cold Resistance",
  "Cold Spell Damage",
  "Cold Vulnerability",
  "Combat Item Damage Percent",
  "Combat Mana Cost",
  "Combat Rate",
  "Conditional Skill (Equipped)",
  "Conditional Skill (Inventory)",
  "Crimbot Outfit Power",
  "Critical Hit Percent",
  "DB Combat Damage",
  "Damage Absorption",
  "Damage Aura",
  "Damage Reduction",
  "Damage vs. Bugbears",
  "Damage vs. Ghosts",
  "Damage vs. Mer-kin",
  "Damage vs. Orcs",
  "Damage vs. Seals",
  "Damage vs. Skeletons",
  "Damage vs. Undead",
  "Damage vs. Vampires",
  "Damage vs. Werewolves",
  "Damage vs. Zombies",
  "Disco Style",
  "Drippy Damage",
  "Drippy Resistance",
  "Drops Items",
  "Drops Meat",
  "Effect",
  "Effect Duration",
  "Elf Warfare Effectiveness",
  "Energy",
  "Equalize",
  "Equalize Moxie",
  "Equalize Muscle",
  "Equalize Mysticality",
  "Equips On",
  "Evaluated Modifiers",
  "Experience",
  "Extra Pickpocket",
  "Fairy",
  "Fairy Effectiveness",
  "Familiar Action Bonus",
  "Familiar Damage",
  "Familiar Effect",
  "Familiar Experience",
  "Familiar Tuning Moxie",
  "Familiar Tuning Muscle",
  "Familiar Tuning Mysticality",
  "Familiar Weight",
  "Familiar Weight Cap",
  "Familiar Weight Percent",
  "Fishing Skill",
  "Floor Buffed Moxie",
  "Floor Buffed Muscle",
  "Floor Buffed Mysticality",
  "Food Drop",
  "Food Fairy",
  "Food Fairy Effectiveness",
  "Four Songs",
  "Free Pull",
  "Free Rests",
  "Fumble",
  "Gear Drop",
  "Generic",
  "HP Regen Max",
  "HP Regen Min",
  "Hat Drop",
  "Hidden Familiar Weight",
  "Hobo Power",
  "Hot Damage",
  "Hot Immunity",
  "Hot Resistance",
  "Hot Spell Damage",
  "Hot Vulnerability",
  "Initiative",
  "Initiative Penalty",
  "Intrinsic Effect",
  "Item Drop",
  "Item Drop Penalty",
  "Jiggle",
  "Kruegerand Drop",
  "Lantern",
  "Lantern Element",
  "Last Available",
  "Lasts Until Rollover",
  "Leaves",
  "Leprechaun",
  "Leprechaun Effectiveness",
  "Liver Capacity",
  "Luck",
  "MP Regen Max",
  "MP Regen Min",
  "MPC Drop",
  "Mana Cost",
  "Maximum HP",
  "Maximum HP Percent",
  "Maximum Hooch",
  "Maximum MP",
  "Maximum MP Percent",
  "Maximum PP",
  "McHugeLarge",
  "Meat Bonus",
  "Meat Drop",
  "Meat Drop Penalty",
  "Minstrel Level",
  "Modifiers",
  "Monster Level",
  "Monster Level Percent",
  "Moxie",
  "Moxie Controls MP",
  "Moxie Experience",
  "Moxie Experience Percent",
  "Moxie Limit",
  "Moxie May Control MP",
  "Moxie Percent",
  "Muscle",
  "Muscle Experience",
  "Muscle Experience Percent",
  "Muscle Limit",
  "Muscle Percent",
  "Mutex Violations",
  "Mutually Exclusive",
  "Mysticality",
  "Mysticality Experience",
  "Mysticality Experience Percent",
  "Mysticality Limit",
  "Mysticality Percent",
  "Negative Status Resist",
  "Never Fumble",
  "No Pull",
  "Nonstackable Watch",
  "Offhand Drop",
  "Othello Skill",
  "Outfit",
  "Pants Drop",
  "Pasta Thrall Experience",
  "Pickpocket Chance",
  "Piece of Twelve Drop",
  "Pirate",
  "Pirate Warfare Effectiveness",
  "Plumber Power",
  "Plumber Stat",
  "Pool Skill",
  "Potion Drop",
  "Prismatic Damage",
  "PvP Fights",
  "RAM",
  "Random Monster Modifiers",
  "Ranged Damage",
  "Ranged Damage Percent",
  "Raveosity",
  "Raw Combat Rate",
  "Recipe",
  "Reduce Enemy Defense",
  "Resting HP Percent",
  "Resting MP Percent",
  "Rollover Effect",
  "Rollover Effect Duration",
  "Rubee Drop",
  "Sauce Spell Damage",
  "Scrap",
  "Shirt Drop",
  "Single Equip",
  "Sixgun Damage",
  "Skill",
  "Sleaze Damage",
  "Sleaze Immunity",
  "Sleaze Resistance",
  "Sleaze Spell Damage",
  "Sleaze Vulnerability",
  "Slime Hates It",
  "Slime Resistance",
  "Smithsness",
  "Softcore Only",
  "Sombrero",
  "Sombrero Bonus",
  "Sombrero Effectiveness",
  "Song Duration",
  "Spell Critical Percent",
  "Spell Damage",
  "Spell Damage Percent",
  "Spleen Capacity",
  "Spleen Drop",
  "Spooky Damage",
  "Spooky Immunity",
  "Spooky Resistance",
  "Spooky Spell Damage",
  "Spooky Vulnerability",
  "Sporadic Damage Aura",
  "Sporadic Item Drop",
  "Sporadic Meat Drop",
  "Sporadic Thorns",
  "Sprinkle Drop",
  "Stackable Mana Cost",
  "Stat Tuning",
  "Stench Damage",
  "Stench Immunity",
  "Stench Resistance",
  "Stench Spell Damage",
  "Stench Vulnerability",
  "Stinky Cheese",
  "Stomach Capacity",
  "Supercold Resistance",
  "Surgeonosity",
  "Synergetic",
  "Thorns",
  "Underwater Combat Rate",
  "Underwater Familiar",
  "Variable",
  "Volleyball",
  "Volleyball Effectiveness",
  "Volleyball or Sombrero",
  "WarBear Armor Penetration",
  "Water",
  "Water Level",
  "Weakens Monster",
  "Weakens Monster on Critical Hit",
  "Weapon Damage",
  "Weapon Damage Percent",
  "Weapon Drop",
  "Wiki Name",
] as const;
