import babelCore from "@babel/core";
import { createHash } from "crypto";
import esbuild from "esbuild";
import { existsSync, promises as fs } from "fs";
import path from "path";
import * as sass from "sass";
import { parse } from "yaml";

function cachedBabelPlugin({ filter, configFile }) {
  const cacheDir = "node_modules/.cache/esbuild-babel";

  return {
    name: "cached-babel",
    async setup(build) {
      const configHash = createHash("sha1")
        .update(await fs.readFile(configFile, "utf8"))
        .digest("hex");

      await fs.mkdir(cacheDir, { recursive: true });

      const usedFiles = new Set();

      build.onLoad({ filter }, async (args) => {
        const contents = await fs.readFile(args.path, "utf8");
        const key = createHash("sha1")
          .update(contents)
          .update(configHash)
          .digest("hex");
        const cacheFile = `${key}.js`;
        usedFiles.add(cacheFile);

        const cachePath = path.join(cacheDir, cacheFile);

        if (existsSync(cachePath)) {
          return { contents: await fs.readFile(cachePath, "utf8") };
        }

        const result = await babelCore.transformAsync(contents, {
          filename: args.path,
          configFile,
        });

        await fs.writeFile(cachePath, result.code);

        return { contents: result.code };
      });

      build.onEnd(async (result) => {
        if (result.errors.length) return;

        const entries = await fs.readdir(cacheDir);
        if (entries.length === usedFiles.size) return;

        await Promise.all(
          entries
            .filter((entry) => !usedFiles.has(entry))
            .map((entry) => fs.unlink(path.join(cacheDir, entry))),
        );
      });
    },
  };
}

function sassPlugin() {
  return {
    name: "sass",
    setup(build) {
      build.onLoad({ filter: /\.scss$/ }, async (args) => {
        const result = sass.compile(args.path);
        return { contents: result.css, loader: "css" };
      });
    },
  };
}

function dataPlugin(sources) {
  const namespace = "data";

  return {
    name: "data",
    setup(build) {
      build.onResolve({ filter: new RegExp(`^${namespace}:`) }, (args) => ({
        path: args.path.slice(namespace.length + 1),
        namespace,
      }));

      build.onLoad({ filter: /.*/, namespace }, (args) => sources[args.path]);
    },
  };
}

function assembleDataPlugin() {
  return {
    name: "assemble-data",
    setup(build) {
      build.onEnd(async (result) => {
        if (result.errors.length) return;

        const HEADER = `# THIS FILE IS GENERATED WITH EACH NEW BUILD\n# DO NOT EDIT THIS FILE DIRECTLY. EDIT THE FILES IN THE /data/ FOLDER THEN RUN 'yarn build'\n\n`;

        const buildDir = "data";
        const releaseDir = "dist/data";

        await fs.mkdir(releaseDir, { recursive: true });

        const entries = await fs.readdir(buildDir, { withFileTypes: true });

        for (const entry of entries) {
          if (!entry.isDirectory() || entry.name === "tracking") continue;

          const dir = path.join(buildDir, entry.name);
          const outFile = path.join(releaseDir, `autoscend_${entry.name}.txt`);

          let output = HEADER;

          // header.txt
          const headerPath = path.join(dir, "header.txt");

          if (!existsSync(headerPath)) continue;

          output += await fs.readFile(headerPath, "utf8");

          const datFiles = (await fs.readdir(dir, { withFileTypes: true }))
            .filter(
              (f) =>
                f.isFile() &&
                f.name !== "header.txt" &&
                !f.name.endsWith(".yml"),
            )
            .map((f) => f.name)
            .sort((a, b) =>
              a.localeCompare(b, undefined, { sensitivity: "base" }),
            );

          for (const file of datFiles) {
            const filename = path.basename(file).split(".", 2)[0];
            const contents = await fs.readFile(path.join(dir, file), "utf8");

            let num = 0;
            for (const line of contents.split(/\r*\n\r*/)) {
              // If comment, or if the file has the same name as the parent
              if (!line || line.startsWith("#") || filename === entry.name) {
                output += `${line}`;
              } else {
                output += `${filename}\t${num}\t${line}`;
                num++;
              }

              output += "\n";
            }
          }

          await fs.writeFile(outFile, output);
        }

        // eslint-disable-next-line no-undef
        console.log("Assembled files.");
      });
    },
  };
}

async function readYaml(filePath) {
  return parse(await fs.readFile(filePath, "utf8"));
}

// Record<groupPath, {name, property, type, description, tags}[]>
async function buildSettingsData() {
  const dir = "data/settings";
  const yamlFiles = (
    await fs.readdir(dir, { recursive: true, withFileTypes: true })
  ).filter(
    (f) => f.isFile() && f.name.endsWith(".yml") && f.name !== "groups.yml",
  );

  const result = {};

  for (const file of yamlFiles) {
    const relativePath = path.relative(
      dir,
      path.join(file.parentPath, file.name),
    );
    const groupPath = relativePath.slice(0, -".yml".length);
    const data = parse(await fs.readFile(path.join(dir, relativePath), "utf8"));

    if (!data) continue;

    result[groupPath] = Object.entries(data).map(([property, value]) => ({
      name: value.name,
      property,
      type: value.type,
      description: value.description,
      default: value.default,
      dropdown: value.dropdown,
      tags: value.tags
        ? Array.isArray(value.tags)
          ? value.tags.join(",")
          : value.tags
        : "",
    }));
  }

  return result;
}

const [browserBuild, settingsData, settingGroups, tracking, packageJson] =
  await Promise.all([
    esbuild.build({
      entryPoints: {
        "react/script": "packages/browser/src/index.tsx",
        "react/main": "packages/browser/src/css/app.scss",
      },
      bundle: true,
      outdir: "dist",
      platform: "browser",
      format: "iife",
      write: false, // Do not write to disk
      minify: true,
      jsx: "automatic",
      plugins: [sassPlugin()],
    }),
    buildSettingsData(),
    readYaml("data/settings/groups.yml"),
    readYaml("data/tracking/tracking.yml"),
    fs.readFile("package.json", "utf8").then(JSON.parse),
    fs.cp("data/resources", "dist", { recursive: true }),
  ]);

const outputText = (name) =>
  browserBuild.outputFiles.find((f) => f.path === path.resolve("dist", name))
    .text;
const reactScriptSource = outputText("react/script.js");
const reactCssSource = outputText("react/main.css");

const kolmafiaRevision = Number(
  packageJson.resolutions.kolmafia.match(/\d+/g)[1],
);

const dataSources = {
  autoscend_settings: {
    contents: JSON.stringify(settingsData),
    loader: "json",
  },
  kolmafia_revision: {
    contents: JSON.stringify(kolmafiaRevision),
    loader: "json",
  },
  setting_groups: {
    contents: JSON.stringify(settingGroups),
    loader: "json",
  },
  tracking: {
    contents: JSON.stringify(tracking),
    loader: "json",
  },
  react_script: { contents: reactScriptSource, loader: "text" },
  react_css: { contents: reactCssSource, loader: "text" },
};

await esbuild.build({
  entryPoints: {
    "relay/relay_autoscend": "packages/relay/src/relay_autoscend.ts",
    "scripts/autoscend": "packages/kolmafia/src/index.ts",
  },
  bundle: true,
  outdir: "dist/",
  external: ["kolmafia"],
  mainFields: ["main", "module"],
  format: "cjs",
  plugins: [
    dataPlugin(dataSources),
    cachedBabelPlugin({
      filter: /\.[jt]sx?$/,
      configFile: "./babel.config.json",
    }),
    assembleDataPlugin(),
  ],
  loader: {
    ".ts": "ts",
    ".css": "text",
  },
});
