import esbuild from "esbuild";
import babel from "esbuild-plugin-babel";
import { existsSync, promises as fs } from "fs";
import path from "path";
import * as sass from "sass";
import { parse } from "yaml";

function sassPlugin() {
  return {
    name: "sass",
    setup(build) {
      build.onLoad({ filter: /\.scss$/ }, async (args) => {
        const result = sass.compile(args.path);
        return { contents: result.css, loader: "css" };
      });
    },
  };
}

function dataPlugin(sources) {
  const namespace = "data";

  return {
    name: "data",
    setup(build) {
      build.onResolve({ filter: new RegExp(`^${namespace}:`) }, (args) => ({
        path: args.path.slice(namespace.length + 1),
        namespace,
      }));

      build.onLoad({ filter: /.*/, namespace }, (args) => sources[args.path]);
    },
  };
}

function assembleDataPlugin() {
  return {
    name: "assemble-data",
    setup(build) {
      build.onEnd(async (result) => {
        if (result.errors.length) return;

        const HEADER = `# THIS FILE IS GENERATED WITH EACH NEW BUILD\n# DO NOT EDIT THIS FILE DIRECTLY. EDIT THE FILES IN THE /BUILD/ FOLDER THEN RUN 'yarn build'\n\n`;

        const buildDir = "BUILD";
        const releaseDir = "RELEASE/data";

        await fs.mkdir(releaseDir, { recursive: true });

        const entries = await fs.readdir(buildDir, { withFileTypes: true });

        for (const entry of entries) {
          if (!entry.isDirectory() || entry.name === "tracking") continue;

          const dir = path.join(buildDir, entry.name);
          const outFile = path.join(releaseDir, `autoscend_${entry.name}.txt`);

          let output = HEADER;

          // header.txt
          const headerPath = path.join(dir, "header.txt");

          if (!existsSync(headerPath)) continue;

          output += await fs.readFile(headerPath, "utf8");

          const datFiles = (await fs.readdir(dir, { withFileTypes: true }))
            .filter(
              (f) =>
                f.isFile() &&
                f.name !== "header.txt" &&
                !f.name.endsWith(".yml"),
            )
            .map((f) => f.name)
            .sort((a, b) =>
              a.localeCompare(b, undefined, { sensitivity: "base" }),
            );

          for (const file of datFiles) {
            const filename = path.basename(file).split(".", 2)[0];
            const contents = await fs.readFile(path.join(dir, file), "utf8");

            let num = 0;
            for (const line of contents.split(/\r*\n\r*/)) {
              // If comment, or if the file has the same name as the parent
              if (!line || line.startsWith("#") || filename === entry.name) {
                output += `${line}`;
              } else {
                output += `${filename}\t${num}\t${line}`;
                num++;
              }

              output += "\n";
            }
          }

          await fs.writeFile(outFile, output);
        }

        console.log("Assembled files.");
      });
    },
  };
}

// Record<groupPath, {name, property, type, description, tags}[]>
async function buildSettingsData() {
  const dir = "BUILD/settings";
  const yamlFiles = (
    await fs.readdir(dir, { recursive: true, withFileTypes: true })
  ).filter(
    (f) => f.isFile() && f.name.endsWith(".yml") && f.name !== "groups.yml",
  );

  const result = {};

  for (const file of yamlFiles) {
    const relativePath = path.relative(
      dir,
      path.join(file.parentPath, file.name),
    );
    const groupPath = relativePath.slice(0, -".yml".length);
    const data = parse(await fs.readFile(path.join(dir, relativePath), "utf8"));

    if (!data) continue;

    result[groupPath] = Object.entries(data).map(([property, value]) => ({
      name: value.name,
      property,
      type: value.type,
      description: value.description,
      tags: value.tags
        ? Array.isArray(value.tags)
          ? value.tags.join(",")
          : value.tags
        : "",
    }));
  }

  return result;
}

const browserBuild = await esbuild.build({
  entryPoints: {
    "react/script": "src/browser/index.tsx",
    "react/main": "src/browser/css/app.scss",
  },
  bundle: true,
  outdir: "dist",
  platform: "browser",
  format: "iife",
  write: false, // Do not write to disk
  minify: true,
  jsx: "automatic",
  plugins: [sassPlugin()],
});

const outputText = (name) =>
  browserBuild.outputFiles.find((f) => f.path === path.resolve("dist", name))
    .text;
const reactScriptSource = outputText("react/script.js");
const reactCssSource = outputText("react/main.css");

async function readYaml(filePath) {
  return parse(await fs.readFile(filePath, "utf8"));
}

const dataSources = {
  autoscend_settings: {
    contents: JSON.stringify(await buildSettingsData()),
    loader: "json",
  },
  setting_groups: {
    contents: JSON.stringify(await readYaml("BUILD/settings/groups.yml")),
    loader: "json",
  },
  tracking: {
    contents: JSON.stringify(await readYaml("BUILD/tracking/tracking.yml")),
    loader: "json",
  },
  react_script: { contents: reactScriptSource, loader: "text" },
  react_css: { contents: reactCssSource, loader: "text" },
};

await esbuild.build({
  entryPoints: {
    "relay/relay_autoscend": "src/relay/relay_autoscend.ts",
    "scripts/autoscend": "src/kolmafia/index.ts",
    "scripts/autoscend/auto_choice_adv":
      "src/kolmafia/autoscend/auto_choice_adv.ts",
    "scripts/autoscend/auto_post_adv":
      "src/kolmafia/autoscend/auto_post_adv.ts",
    "scripts/autoscend/auto_pre_adv": "src/kolmafia/autoscend/auto_pre_adv.ts",
  },
  bundle: true,
  outdir: "RELEASE/",
  external: ["kolmafia"],
  mainFields: ["main"],
  format: "cjs",
  plugins: [
    dataPlugin(dataSources),
    babel({
      filter: /\.[jt]sx?$/,
      configFile: "./babel.config.json",
    }),
    assembleDataPlugin(),
  ],
  loader: {
    ".ts": "ts",
    ".css": "text",
  },
});
