// esbuild.mjs
import esbuild from "esbuild";
import babel from "esbuild-plugin-babel";
import { promises as fs } from "fs";
import path from "path";

function assembleDataPlugin() {
  return {
    name: "assemble-data",
    setup(build) {
      build.onEnd(async (result) => {
        if (result.errors.length) return;

        const HEADER = `# THIS FILE IS GENERATED WITH EACH NEW BUILD\n# DO NOT EDIT THIS FILE DIRECTLY. EDIT THE .DAT FILES IN THE /BUILD/ FOLDER THEN RUN 'yarn build'\n\n`;

        const buildDir = "BUILD";
        const releaseDir = "RELEASE/data";

        await fs.mkdir(releaseDir, { recursive: true });

        const entries = await fs.readdir(buildDir, { withFileTypes: true });

        for (const entry of entries) {
          if (!entry.isDirectory()) continue;

          const dir = path.join(buildDir, entry.name);
          const outFile = path.join(releaseDir, `autoscend_${entry.name}.txt`);

          let output = HEADER;

          // header.txt
          const headerPath = path.join(dir, "header.txt");
          output += await fs.readFile(headerPath, "utf8");

          // Ignore header files, include all other files, sorted case-insensitively
          const datFiles = (await fs.readdir(dir))
            .filter((f) => path.basename(f) !== "header.txt")
            .sort((a, b) =>
              a.localeCompare(b, undefined, { sensitivity: "base" }),
            );

          for (const file of datFiles) {
            const filename = path.basename(file).split(".", 2)[0];
            const contents = await fs.readFile(path.join(dir, file), "utf8");

            let num = 0;
            for (const line of contents.split(/\r*\n\r*/)) {
              // If comment, or if the file has the same name as the parent
              if (!line || line.startsWith("#") || filename === entry.name) {
                output += `${line}`;
              } else {
                output += `${filename}\t${num}\t${line}`;
                num++;
              }

              output += "\n";
            }
          }

          await fs.writeFile(outFile, output);
        }

        console.log("Assembled data files.");
      });
    },
  };
}

await esbuild.build({
  entryPoints: {
    "relay/relay_autoscend": "src/relay_autoscend.ts",
    "scripts/autoscend": "src/index.ts",
    "scripts/autoscend/auto_choice_adv": "src/autoscend/auto_choice_adv.ts",
    "scripts/autoscend/auto_post_adv": "src/autoscend/auto_post_adv.ts",
    "scripts/autoscend/auto_pre_adv": "src/autoscend/auto_pre_adv.ts",
  },
  bundle: true,
  outdir: "RELEASE/",
  external: ["kolmafia"],
  mainFields: ["main"],
  format: "cjs",
  plugins: [
    babel({
      filter: /\.[jt]sx?$/,
      configFile: "./babel.config.json",
    }),
    assembleDataPlugin(),
  ],
  loader: {
    ".ts": "ts",
  },
});
