name: CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Enable Corepack
      run: corepack enable

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 26
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Publish release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cp -r RELEASE /tmp/release

        git config user.name "Build Script"
        git config user.email "<>"
        git fetch --all
        git switch releases

        git rm -rf --ignore-unmatch .
        cp -r /tmp/release/. .
        git add .
        git commit -m "Build Mafia files for commit $GITHUB_SHA"
        git push origin releases
